#!/bin/bash

echo "current directory1: ${PWD} "
echo "insalling textract prereq"
sudo apt-get install libxml2-dev libxslt1-dev antiword unrtf poppler-utils pstotext tesseract-ocr flac ffmpeg lame libmad0 libsox-fmt-mp3 libpulse-dev sox swig swig3.0 libjpeg-dev zlib1g-dev


echo "current directory2: ${PWD} "
echo "insalling textract "
sudo pip install textract

echo "Installing graphlab"
sudo pip install --upgrade --no-cache-dir https://get.graphlab.com/GraphLab-Create/2.1/sunita@live.unc.edu/0295-EBD3-1F14-E97A-7FA1-5421-EA06-209A/GraphLab-Create-License.tar.gz

echo "Installing configObj"
pip install configobj

echo "Installing gensim"
pip install gensim

echo "Installing pyLDAvis"
pip install pyLDAvis
